# Generated by Django 5.0.3 on 2024-11-06 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0002_alter_employeeprofile_experience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeprofile",
            old_name="Phone",
            new_name="phone",
        ),
    ]
