# Generated by Django 5.0.3 on 2024-11-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("employee", "Employee"), ("employer", "Employer")],
                default="Employee",
                max_length=10,
            ),
        ),
    ]
